# Generated by Django 3.0.8 on 2020-08-13 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_file',
            name='file',
            field=models.FileField(upload_to='D:\\roof_node\\audvik\\files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
