# Generated by Django 3.0.8 on 2020-08-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up_store', '0002_auto_20200813_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csv_file',
        ),
    ]
